// 카카오모먼트 개인회생 잠재고객 수집 광고 — 소재 100종 데이터 (광고주: 법무법인 명율)
// 표기: headline 의 **강조** 는 포인트 컬러, \n 은 줄바꿈
// layout: hero | type | number | ox | check | steps | stat
// theme : navy | charcoal | night | blue | teal | white | ivory | sand | peach | mint
// title ≤25자, promo ≤45자 (카카오 디스플레이 타이틀·홍보문구), biz = [비즈보드 메인, 서브]
// risk  : low(사실·제도 설명) | mid(계산 예시·조건부 효과 등 사람 확인 권장)

export const CONCEPTS = {
  A: { name: '독촉·추심 멈춤', type: '고통 해소형', bizIcon: 'bell_with_slash', hook: '지금 가장 괴로운 순간(전화·문자·압류)을 짚고, 법이 정한 멈춤 장치(금지·중지명령)를 알린다' },
  B: { name: '월 변제금 숫자', type: '계산 예시형', bizIcon: 'abacus', hook: '월 변제금 = 소득 − 생계비. 2026년 법원 생계비로 계산한 예시를 조건과 함께 보여준다' },
  C: { name: '감정 공감', type: '공감형', bizIcon: 'crescent_moon', hook: '새벽 빚 계산, 월급날 불안 등 말 못 할 순간에 공감하고 상담의 문턱을 낮춘다' },
  D: { name: '오해와 사실', type: 'O/X 팩트형', bizIcon: 'magnifying_glass_tilted_right', hook: '신청을 막는 흔한 오해를 O/X로 바로잡는다' },
  E: { name: '셀프 체크', type: '자가 진단형', bizIcon: 'clipboard', hook: '"나도 해당될까?"를 스스로 확인하게 해 클릭 동기를 만든다' },
  F: { name: '직업·상황 호명', type: '타깃 호명형', bizIcon: 'briefcase', hook: '직장인·사장님·프리랜서·공무원 등 대상을 직접 부른다' },
  G: { name: '제도 핵심 정보', type: '정보 제공형', bizIcon: 'balance_scale', hook: '개인회생의 구조·절차·주의점을 짧게 알려 신뢰를 쌓는다' },
  H: { name: '비밀·안심', type: '불안 해소형', bizIcon: 'locked', hook: '가족·직장에 알려질까, 절차가 복잡할까 하는 걱정을 사실로 누그러뜨린다' },
  I: { name: '숫자로 보는 현실', type: '사회적 증거형', bizIcon: 'bar_chart', hook: '공식 통계로 "나만의 문제가 아니다"를 보여준다 (출처 표기)' },
  J: { name: '위트·밈', type: '유머형', bizIcon: 'money_with_wings', hook: '월급 스침·돌려막기 등 공감 밈으로 피드에서 멈추게 한다' },
};

// 2026년 법원 인정 생계비(기준 중위소득 60%, 원 단위 절사)
export const LIVING_COST_2026 = { 1: 1538542, 2: 2519575, 3: 3215421, 4: 3896842 };

// 검증된 수치 출처 (규정 검사기의 수치 근거로 사용)
export const SOURCES = {
  court2026h1: '법원행정처 2026년 상반기 개인회생 신청 81,723건 8만 1,723건 전년 동기 72,192건 13.2% 증가 10년 전 상반기 47,229건 4만 7,229건 1.7배 하루 평균 약 450건 8만 건',
  yearbook2025: '2026 사법연감 2025년 개인회생 149,147건 14만 9천여 건 개인파산 40,909건 4만 909건',
  seoulYouth: '서울시 조사 2025년 신청 29세 이하 1,025명 평균 채무 6,926만 원 생활비 67.9% 10명 중 약 7명',
  seoulCourt2030: '서울회생법원 2025 개인회생 통계조사보고서 20·30대 개시결정 2022년 6,913건 2023년 9,171건 32.7%',
  law: '채무자회생법 제579조 무담보 10억 원 담보 15억 원 제611조 3년 5년 2018년 제619조 제600조 국가공무원법 제33조 변호사법 제26조 민사소송법 제184조',
  living: '2026년 생계비 1인 153만 8,542원 4인 389만 6,842원 389만 원',
};

const C = (o) => o;
export const CREATIVES = [];
const add = (...items) => CREATIVES.push(...items.map(C));

// ── A. 독촉·추심 멈춤 ─────────────────────────────
add(
  { id: 1, code: 'A01', slug: 'collection-call-stop', layout: 'hero', theme: 'navy', icons: ['bell_with_slash'], eyebrow: '개인회생 금지명령',
    headline: '매일 오는 **독촉 전화**\n멈추는 방법이 있습니다', sub: '법원 금지명령이 나오면 추심이 금지됩니다', note: '금지명령 여부는 법원이 결정합니다',
    title: '독촉 전화, 법으로 멈추는 방법', promo: '개인회생 금지명령이 나오면 채권자의 추심이 금지됩니다. 상담 신청하세요', biz: ['독촉 전화 멈추는 방법', '개인회생 금지명령 상담'], risk: 'low', src: 'law' },
  { id: 2, code: 'A02', slug: 'collection-text-panic', layout: 'hero', theme: 'charcoal', icons: ['incoming_envelope'],
    headline: '독촉 문자에\n**가슴이 철렁**한다면', sub: '개인회생 금지명령부터 확인하세요',
    title: '독촉 문자, 이제 그만 받고 싶다면', promo: '개인회생을 신청하며 금지명령도 함께 신청할 수 있습니다. 비공개 상담 신청', biz: ['독촉 문자에 가슴이 철렁', '금지명령부터 확인하세요'], risk: 'low' },
  { id: 3, code: 'A03', slug: 'salary-seizure', layout: 'hero', theme: 'navy', icons: ['broken_chain', 'money_with_wings'], eyebrow: '급여 압류',
    headline: '월급 압류,\n**풀 수 있는 길**이 있습니다', sub: '개시결정이 나면 압류 절차가 중지됩니다', note: '중지·해제 여부는 법원이 결정합니다',
    title: '급여 압류 중이어도 개인회생 가능', promo: '급여가 압류된 상태에서도 개인회생을 신청할 수 있습니다. 중지명령 상담 신청', biz: ['월급 압류, 풀 수 있는 길', '압류 중에도 신청 가능'], risk: 'mid', src: 'law' },
  { id: 4, code: 'A04', slug: 'stacked-notices', layout: 'hero', theme: 'ivory', icons: ['envelope', 'house'],
    headline: '쌓여 가는 독촉장\n**더 늦기 전에**', sub: '개인회생으로 추심을 멈출 방법이 있습니다',
    title: '쌓이는 독촉장, 방법이 있습니다', promo: '독촉장이 쌓이고 있다면 개인회생 금지명령을 확인해 보세요. 1분 상담 신청', biz: ['쌓여 가는 독촉장', '더 늦기 전에 확인하세요'], risk: 'low' },
  { id: 5, code: 'A05', slug: 'stop-collection', layout: 'type', theme: 'charcoal', icons: ['stop_sign'],
    headline: '독촉·추심\n**멈추는 법**', sub: '개인회생 금지명령, 신청할 수 있습니다',
    title: '독촉과 추심, 멈추는 법이 있습니다', promo: '개인회생을 신청하면서 금지명령을 함께 신청할 수 있습니다. 지금 상담 신청', biz: ['독촉 추심 멈추는 법', '개인회생 금지명령'], risk: 'low' },
  { id: 6, code: 'A06', slug: 'night-calls', layout: 'hero', theme: 'night', icons: ['crescent_moon', 'mobile_phone_off'],
    headline: '밤에도 울리는 전화\n**끝낼 방법**이 있습니다', sub: '금지명령으로 추심을 막을 수 있습니다',
    title: '밤에도 울리는 독촉 전화라면', promo: '개인회생 금지명령 결정 이후엔 채권자가 추심할 수 없습니다. 비공개 상담 신청', biz: ['밤에도 울리는 독촉 전화', '끝낼 방법이 있습니다'], risk: 'low' },
  { id: 7, code: 'A07', slug: 'all-creditors-once', layout: 'hero', theme: 'white', icons: ['credit_card', 'bank', 'receipt'],
    headline: '카드·은행·대부업\n**한 번에 정리**하는 절차', sub: '여러 빚을 하나의 변제계획으로 갚습니다',
    title: '카드, 은행, 대부업 빚을 한 번에', promo: '여러 곳의 빚을 하나의 변제계획으로 정리하는 개인회생. 1분 상담 신청', biz: ['여러 곳 빚, 한 번에 정리', '하나의 변제계획으로'], risk: 'low' },
  { id: 8, code: 'A08', slug: 'afraid-of-calls', layout: 'hero', theme: 'sand', icons: ['anxious_face_with_sweat'],
    headline: '전화 받기가\n**무서워졌다면**', sub: '혼자 버티지 말고 법적 절차를 확인하세요',
    title: '독촉 전화가 무서워졌다면', promo: '추심 스트레스, 혼자 버티지 마세요. 개인회생 절차를 변호사와 확인하세요', biz: ['전화 받기가 무서워졌다면', '혼자 버티지 마세요'], risk: 'low' },
  { id: 9, code: 'A09', slug: 'seizure-notice', layout: 'hero', theme: 'white', icons: ['page_facing_up', 'locked'],
    headline: '압류 통지서를\n**받으셨나요?**', sub: '개인회생 중지명령을 검토해 보세요', note: '중지 여부는 법원이 결정합니다',
    title: '압류 통지서를 받으셨다면', promo: '압류가 시작됐어도 개인회생을 신청할 수 있습니다. 중지명령 상담 신청', biz: ['압류 통지서를 받으셨나요', '중지명령을 검토하세요'], risk: 'low' },
  { id: 10, code: 'A10', slug: 'plan-not-chase', layout: 'hero', theme: 'teal', icons: ['spiral_calendar', 'seedling'],
    headline: '쫓기듯 갚는 대신\n**계획대로 갚는 삶**', sub: '원칙 3년, 소득에 맞춘 변제계획',
    title: '쫓기지 말고 계획대로 갚으세요', promo: '소득에 맞춘 변제계획으로 원칙 3년간 갚는 개인회생. 상담 신청하세요', biz: ['쫓기듯 갚는 대신', '계획대로 갚는 개인회생'], risk: 'low', src: 'law' },
);

// ── B. 월 변제금 숫자 (계산 예시는 2026년 생계비 기준, 재산 없음 가정) ─────
const ex = (h, inc) => `예시: ${h}인 가구, 월 소득 ${inc}만 원, 재산 없음 가정. 실제 금액은 법원이 정합니다`;
add(
  { id: 11, code: 'B01', slug: 'payment-formula', layout: 'type', theme: 'white', icons: ['abacus'], eyebrow: '개인회생 월 변제금',
    headline: '월 변제금은\n**소득 − 생계비**', sub: '빚 크기보다 소득이 기준입니다', note: '원칙적인 계산 방식이며 재산 등에 따라 달라질 수 있습니다',
    title: '월 변제금은 이렇게 정해집니다', promo: '개인회생 월 변제금은 소득에서 생계비를 뺀 금액이 기준입니다. 상담 신청', biz: ['월 변제금 = 소득 - 생계비', '빚 크기보다 소득이 기준'], risk: 'low' },
  { id: 12, code: 'B02', slug: 'example-50m-1p', layout: 'number', theme: 'white', calc: { debt: 50000000, income: 2000000, household: 1 },
    num: { label: '총 채무 5,000만 원', pre: '월 변제금 약', value: '46', unit: '만 원', caption: '36개월 변제 계산 예시' },
    headline: '총 채무 5,000만 원\n월 변제금은 약 **46만 원**', note: ex(1, 200),
    title: '빚 5천만 원, 월 변제금 계산 예시', promo: '1인 가구 월 소득 200만 원이면 월 약 46만 원(예시). 상담으로 확인하세요', biz: ['월 변제금 계산 예시', '1인 가구 월 소득 200만 원'], risk: 'mid' },
  { id: 13, code: 'B03', slug: 'example-80m-3p', layout: 'number', theme: 'ivory', calc: { debt: 80000000, income: 3500000, household: 3 },
    num: { label: '총 채무 8,000만 원', pre: '월 변제금 약', value: '28', unit: '만 원', caption: '3인 가구 36개월 계산 예시' },
    headline: '총 채무 8,000만 원\n월 변제금은 약 **28만 원**', note: ex(3, 350),
    title: '3인 가족 가장의 월 변제금 예시', promo: '3인 가구 월 소득 350만 원이면 월 약 28만 원(예시). 상담으로 확인하세요', biz: ['3인 가구 월 변제금 예시', '월 소득 350만 원 기준'], risk: 'mid' },
  { id: 14, code: 'B04', slug: 'example-120m-4p', layout: 'number', theme: 'navy', calc: { debt: 120000000, income: 4200000, household: 4 },
    num: { label: '총 채무 1억 2,000만 원', pre: '월 변제금 약', value: '30', unit: '만 원', caption: '4인 가구 36개월 계산 예시' },
    headline: '총 채무 1억 2,000만 원\n월 변제금은 약 **30만 원**', note: ex(4, 420),
    title: '빚 1억 넘어도 월 변제금은 소득 기준', promo: '4인 가구 월 소득 420만 원이면 월 약 30만 원(예시). 1분 상담 신청', biz: ['빚 1억 넘어도 소득 기준', '4인 가구 월 약 30만 원 예시'], risk: 'mid' },
  { id: 15, code: 'B05', slug: 'example-45m-2p', layout: 'number', theme: 'sand', calc: { debt: 45000000, income: 2800000, household: 2 },
    num: { label: '총 채무 4,500만 원', pre: '월 변제금 약', value: '28', unit: '만 원', caption: '2인 가구 36개월 계산 예시' },
    headline: '총 채무 4,500만 원\n월 변제금은 약 **28만 원**', note: ex(2, 280),
    title: '2인 가구 월 변제금 계산 예시', promo: '2인 가구 월 소득 280만 원이면 월 약 28만 원(예시). 내 금액은 상담으로', biz: ['2인 가구 월 변제금 예시', '월 소득 280만 원 기준'], risk: 'mid' },
  { id: 16, code: 'B06', slug: 'example-30m-1p', layout: 'number', theme: 'white', calc: { debt: 30000000, income: 1700000, household: 1 },
    num: { label: '총 채무 3,000만 원', pre: '월 변제금 약', value: '16', unit: '만 원', caption: '36개월 변제 계산 예시' },
    headline: '총 채무 3,000만 원\n월 변제금은 약 **16만 원**', note: ex(1, 170),
    title: '월 소득 170만 원, 변제금 예시', promo: '1인 가구 월 소득 170만 원이면 월 약 16만 원(예시). 상담 신청하세요', biz: ['월 소득 170만 원이라면', '월 변제금 약 16만 원 예시'], risk: 'mid' },
  { id: 17, code: 'B07', slug: 'living-cost-2026', layout: 'stat', theme: 'ivory',
    stat: { label: '2026년 1인 가구 인정 생계비', value: '153만 8,542', unit: '원' },
    headline: '이 금액은 **먼저 남기고**\n변제금을 정합니다', note: '법원 기준 생계비(기준 중위소득 60%)',
    title: '생계비는 먼저 남기고 갚습니다', promo: '개인회생은 법원 기준 생계비를 먼저 남기고 나머지로 갚는 제도입니다', biz: ['생계비는 먼저 남깁니다', '1인 가구 153만 8,542원'], risk: 'low', src: 'living' },
  { id: 18, code: 'B08', slug: 'three-years', layout: 'type', theme: 'blue', icons: ['spiral_calendar'],
    headline: '갚는 기간은\n원칙 **3년**', sub: '특별한 사정이 있을 때만 최장 5년', note: '채무자회생법 제611조',
    title: '개인회생 변제기간, 원칙은 3년', promo: '개인회생 변제기간은 원칙 3년입니다. 내 월 변제금은 상담으로 확인하세요', biz: ['변제기간 원칙은 3년', '특별한 사정이 있을 때만 5년'], risk: 'low', src: 'law' },
  { id: 19, code: 'B09', slug: 'debt-size-vs-income', layout: 'hero', theme: 'charcoal', icons: ['abacus'],
    headline: '빚이 1억이어도\n**소득에 맞춰** 갚습니다', sub: '월 변제금은 소득 − 생계비가 기준', note: '재산이 있으면 재산 가치 이상을 갚아야 합니다',
    title: '빚이 커도 소득에 맞춰 갚습니다', promo: '개인회생 월 변제금은 빚 총액이 아니라 소득과 생계비를 기준으로 정합니다', biz: ['빚이 1억이어도', '소득에 맞춰 갚습니다'], risk: 'low' },
  { id: 20, code: 'B10', slug: 'discharge-after', layout: 'hero', theme: 'teal', icons: ['sunrise_over_mountains'],
    headline: '계획대로 다 갚으면\n**남은 빚은 면책**', sub: '변제를 마치면 법원이 면책을 결정합니다', note: '벌금·세금 등 일부 채무는 면책되지 않습니다',
    title: '다 갚으면 남은 빚은 면책됩니다', promo: '개인회생은 변제계획을 마치면 남은 채무를 면책받는 제도입니다. 상담 신청', biz: ['다 갚으면 남은 빚은 면책', '변제를 마치면 법원이 결정'], risk: 'mid' },
);

// ── C. 감정 공감 ─────────────────────────────
add(
  { id: 21, code: 'C01', slug: 'dawn-3am', layout: 'hero', theme: 'night', icons: ['waning_crescent_moon', 'alarm_clock'],
    headline: '새벽 3시,\n또 **빚 계산** 중인가요', sub: '혼자 계산하지 말고 방법부터 확인하세요',
    title: '잠 못 들고 빚 계산 중이라면', promo: '새벽까지 이어지는 빚 걱정, 개인회생으로 정리할 방법이 있는지 확인하세요', biz: ['새벽 3시, 또 빚 계산 중', '방법부터 확인하세요'], risk: 'low' },
  { id: 22, code: 'C02', slug: 'payday-fear', layout: 'hero', theme: 'peach', icons: ['money_with_wings'],
    headline: '월급날이\n**더 두려운** 당신에게', sub: '들어오자마자 빠져나가는 월급이라면',
    title: '월급날이 더 두려워졌다면', promo: '월급이 들어오자마자 빚으로 빠져나간다면 개인회생을 검토해 보세요', biz: ['월급날이 더 두렵다면', '개인회생을 검토하세요'], risk: 'low' },
  { id: 23, code: 'C03', slug: 'interest-only-year', layout: 'hero', theme: 'sand', icons: ['hourglass_not_done'],
    headline: '이자만 갚다가\n**1년**이 지났다면', sub: '원금이 그대로라면 구조를 바꿔야 합니다',
    title: '이자만 갚다 1년이 지났다면', promo: '원금은 그대로, 이자만 갚고 있다면 개인회생으로 구조를 바꿀 수 있습니다', biz: ['이자만 갚다 1년 지났다면', '원금이 줄지 않는다면'], risk: 'low' },
  { id: 24, code: 'C04', slug: 'secret-from-family', layout: 'hero', theme: 'navy', icons: ['locked'],
    headline: '가족에게\n**말 못 한 빚**이 있다면', sub: '비공개로 먼저 상담해 보세요', note: '상담 내용은 변호사법상 비밀유지 의무 대상입니다',
    title: '가족에게 말 못 한 빚이 있다면', promo: '혼자 끙끙 앓던 빚 고민, 비공개 상담으로 먼저 방법을 확인하세요', biz: ['가족에게 말 못 한 빚', '비공개로 먼저 상담하세요'], risk: 'low', src: 'law' },
  { id: 25, code: 'C05', slug: 'card-juggling', layout: 'hero', theme: 'white', icons: ['credit_card', 'credit_card'],
    headline: '돌려막기 **몇 달째**,\n이제 멈춰도 됩니다', sub: '카드값으로 카드값을 막고 있다면',
    title: '카드 돌려막기, 이제 멈추세요', promo: '카드값을 카드로 막는 악순환, 개인회생으로 끊을 수 있는지 확인하세요', biz: ['돌려막기 몇 달째인가요', '이제 멈춰도 됩니다'], risk: 'low' },
  { id: 26, code: 'C06', slug: 'not-your-fault', layout: 'hero', theme: 'mint', icons: ['dove'],
    headline: '빚, 당신 잘못만은\n**아닙니다**', sub: '생활비로 시작된 빚도 정리할 방법이 있습니다',
    title: '빚, 당신 잘못만은 아닙니다', promo: '생활비로 시작된 빚도 개인회생 제도로 정리할 수 있습니다. 비공개 상담 신청', biz: ['당신 잘못만은 아닙니다', '생활비로 시작된 빚이라면'], risk: 'low' },
  { id: 27, code: 'C07', slug: 'pretending-ok', layout: 'hero', theme: 'ivory', icons: ['face_exhaling'],
    headline: '오늘도 **괜찮은 척**\n하고 계신가요', sub: '빚 문제, 법률 상담으로 방법부터 찾으세요',
    title: '괜찮은 척, 이제 그만해도 됩니다', promo: '혼자 버티던 빚 문제, 변호사와 상담하며 법적 해결 방법을 확인하세요', biz: ['오늘도 괜찮은 척 중이라면', '방법부터 찾아보세요'], risk: 'low' },
  { id: 28, code: 'C08', slug: 'interest-over-tuition', layout: 'hero', theme: 'peach', icons: ['backpack', 'receipt'],
    headline: '아이 학원비보다\n**이자가 더 큰** 달', sub: '개인회생은 생계비를 먼저 남기고 갚습니다',
    title: '이자가 생활비를 넘어섰다면', promo: '개인회생은 가족 생계비를 먼저 인정하고 남는 소득으로 갚는 제도입니다', biz: ['학원비보다 이자가 크다면', '생계비부터 남기고 갚아요'], risk: 'low' },
  { id: 29, code: 'C09', slug: 'sleep-again', layout: 'hero', theme: 'night', icons: ['bed', 'crescent_moon'],
    headline: '다시 **편히 자는 밤**을\n찾고 싶다면', sub: '빚 정리 방법, 상담으로 확인하세요',
    title: '다시 편히 자고 싶다면', promo: '빚 걱정으로 잠 못 드는 밤, 개인회생으로 정리할 수 있는지 확인하세요', biz: ['다시 편히 자고 싶다면', '빚 정리 방법 확인하기'], risk: 'low' },
  { id: 30, code: 'C10', slug: 'before-conclusion', layout: 'hero', theme: 'teal', icons: ['sunrise'],
    headline: '혼자 결론 내리기 전에\n**한 번만** 확인하세요', sub: '법이 정한 채무 조정 절차가 있습니다',
    title: '혼자 결론 내리기 전에 확인하세요', promo: '갚을 방법이 없다고 느껴질 때, 법원 개인회생 절차부터 확인해 보세요', biz: ['혼자 결론 내리기 전에', '법이 정한 절차가 있어요'], risk: 'low' },
);

// ── D. 오해와 사실 (ox: 'X' 오해 / 'O' 사실, headline=질문, sub=답) ─────
add(
  { id: 31, code: 'D01', slug: 'myth-company-notice', layout: 'ox', theme: 'white', ox: 'X',
    headline: '개인회생하면\n**회사에 알려진다?**', sub: '법원이 회사에 따로 알리지 않습니다', note: '급여 압류가 없는 경우입니다',
    title: '개인회생하면 회사에 알려질까?', promo: '급여 압류가 없다면 법원이 회사에 개인회생 사실을 따로 알리지 않습니다', biz: ['회사에 알려질까 걱정이라면', '법원은 따로 알리지 않아요'], risk: 'mid' },
  { id: 32, code: 'D02', slug: 'myth-min-debt', layout: 'ox', theme: 'ivory', ox: 'X',
    headline: '빚이 적으면\n**개인회생 못 한다?**', sub: '법에 정한 최저 채무액은 없습니다',
    title: '빚이 적어도 개인회생 가능할까?', promo: '개인회생은 법에 정한 최저 채무액이 없습니다. 내 상황에 맞는지 상담 신청', biz: ['빚이 적어도 개인회생 가능', '최저 채무액 기준 없음'], risk: 'low' },
  { id: 33, code: 'D03', slug: 'myth-need-default', layout: 'ox', theme: 'blue', ox: 'X',
    headline: '연체가 있어야\n**신청할 수 있다?**', sub: '연체 전이어도 신청할 수 있습니다', note: '갚기 어려워질 염려가 있으면 신청 가능 (채무자회생법 제579조)',
    title: '연체 전인데 개인회생 가능할까?', promo: '빚을 갚기 어려워질 염려가 있다면 연체 전에도 개인회생을 신청할 수 있습니다', biz: ['연체 전에도 신청 가능', '개인회생 요건 확인하기'], risk: 'low', src: 'law' },
  { id: 34, code: 'D04', slug: 'myth-homeowner', layout: 'ox', theme: 'white', ox: 'X',
    headline: '집이 있으면\n**개인회생 못 한다?**', sub: '재산이 있어도 신청할 수 있습니다', note: '재산 가치 이상을 갚도록 계획을 세웁니다',
    title: '집이 있어도 개인회생 가능할까?', promo: '재산이 있어도 개인회생을 신청할 수 있습니다. 재산 가치를 반영해 계획합니다', biz: ['집이 있어도 개인회생', '재산이 있어도 신청 가능'], risk: 'low' },
  { id: 35, code: 'D05', slug: 'fact-freelancer', layout: 'ox', theme: 'mint', ox: 'O',
    headline: '알바·프리랜서도\n**신청할 수 있다?**', sub: '반복되는 소득이 있으면 가능합니다',
    title: '알바, 프리랜서도 개인회생 되나요?', promo: '반복적인 소득이 있다면 알바, 프리랜서도 개인회생을 신청할 수 있습니다', biz: ['알바, 프리랜서도 가능', '반복 소득이 있다면'], risk: 'low' },
  { id: 36, code: 'D06', slug: 'fact-private-lender', layout: 'ox', theme: 'white', ox: 'O',
    headline: '대부업 빚도\n**개인회생에 포함?**', sub: '대부업체 빚도 변제계획에 포함됩니다',
    title: '대부업 빚도 개인회생 되나요?', promo: '은행과 카드사뿐 아니라 대부업체 빚도 개인회생 변제계획에 포함됩니다', biz: ['대부업 빚도 포함됩니다', '개인회생 변제계획'], risk: 'low' },
  { id: 37, code: 'D07', slug: 'myth-family-debt', layout: 'ox', theme: 'ivory', ox: 'X',
    headline: '개인회생하면\n**가족 빚도 정리된다?**', sub: '신청한 본인 명의 빚만 대상입니다',
    title: '배우자 빚도 함께 정리될까?', promo: '개인회생은 신청한 본인 명의 채무만 대상입니다. 부부 모두 상담 가능합니다', biz: ['가족 빚도 정리될까', '본인 명의 빚만 대상'], risk: 'low' },
  { id: 38, code: 'D08', slug: 'fact-keep-job', layout: 'ox', theme: 'blue', ox: 'O',
    headline: '개인회생 중에도\n**직장은 그대로?**', sub: '일하며 소득으로 갚는 절차입니다',
    title: '개인회생 중에도 회사 다니나요?', promo: '개인회생은 일을 계속하며 소득으로 갚는 절차입니다. 궁금한 점은 상담으로', biz: ['개인회생 중 직장은?', '일하며 갚는 절차입니다'], risk: 'low' },
  { id: 39, code: 'D09', slug: 'myth-workout', layout: 'ox', theme: 'white', ox: 'X',
    headline: '워크아웃 중이면\n**개인회생 못 한다?**', sub: '채무조정 중에도 신청할 수 있습니다',
    title: '워크아웃 중인데 개인회생 가능?', promo: '워크아웃 등 채무조정을 이용 중이어도 법원 개인회생을 신청할 수 있습니다', biz: ['워크아웃 중에도 신청 가능', '원금 부담이 크다면'], risk: 'low' },
  { id: 40, code: 'D10', slug: 'myth-five-years', layout: 'ox', theme: 'mint', ox: 'X',
    headline: '개인회생은\n**무조건 5년 갚는다?**', sub: '변제기간은 원칙 3년입니다', note: '채무자회생법 제611조',
    title: '개인회생 5년? 원칙은 3년입니다', promo: '개인회생 변제기간은 원칙 3년, 특별한 사정이 있을 때 최장 5년입니다', biz: ['무조건 5년? 원칙은 3년', '개인회생 변제기간'], risk: 'low', src: 'law' },
);

// ── E. 셀프 체크 ─────────────────────────────
add(
  { id: 41, code: 'E01', slug: 'check-two-of-three', layout: 'check', theme: 'charcoal', checks: ['매달 들어오는 소득이 있다', '빚이 1년 소득보다 많다', '이자 갚기도 버겁다'],
    headline: '3개 중 **2개 이상**이라면', sub: '개인회생을 검토해 볼 때입니다', note: '신청 가능 여부는 상담으로 확인하세요',
    title: '개인회생, 나도 해당될까?', promo: '소득이 있고 빚 부담이 크다면 개인회생을 검토해 볼 수 있습니다. 1분 상담', biz: ['3개 중 2개 이상이라면', '개인회생 검토해 보세요'], risk: 'low' },
  { id: 42, code: 'E02', slug: 'debt-over-salary', layout: 'hero', theme: 'white', icons: ['chart_increasing'],
    headline: '빚이 **연봉보다**\n많아졌나요?', sub: '갚는 속도보다 이자가 빠르다면 신호입니다',
    title: '빚이 연봉보다 많아졌다면', promo: '빚이 소득보다 빠르게 늘고 있다면 개인회생 상담으로 방법을 확인하세요', biz: ['빚이 연봉보다 많다면', '개인회생을 검토하세요'], risk: 'low' },
  { id: 43, code: 'E03', slug: 'three-lenders', layout: 'hero', theme: 'blue', icons: ['credit_card', 'bank', 'money_bag'],
    headline: '대출이\n**3곳 이상**이라면', sub: '여러 빚을 한 번에 조정하는 제도가 있습니다',
    title: '대출이 3곳 이상이라면', promo: '카드론, 신용대출, 대부업까지 여러 빚을 하나의 변제계획으로 정리하세요', biz: ['대출이 3곳 이상이라면', '한 번에 조정하는 제도'], risk: 'low' },
  { id: 44, code: 'E04', slug: 'half-salary-to-debt', layout: 'hero', theme: 'sand', icons: ['receipt'],
    headline: '월급의 **절반 이상**이\n빚으로 나간다면', sub: '생계비를 먼저 남기는 개인회생을 검토하세요',
    title: '월급 절반이 빚으로 나간다면', promo: '소득의 절반 이상이 원리금으로 나간다면 개인회생 상담을 받아 보세요', biz: ['월급 절반이 빚으로 나간다면', '개인회생을 검토하세요'], risk: 'low' },
  { id: 45, code: 'E05', slug: 'loan-rejected', layout: 'hero', theme: 'charcoal', icons: ['no_entry'],
    headline: '최근 **대출 거절**\n당하셨나요?', sub: '돌려막기가 막혔다면 다른 방법이 필요합니다',
    title: '대출이 막혔다면 확인하세요', promo: '추가 대출이 막혀 돌려막기가 어렵다면 개인회생으로 구조를 바꿔 보세요', biz: ['최근 대출 거절 당했다면', '다른 방법이 필요합니다'], risk: 'low' },
  { id: 46, code: 'E06', slug: 'cash-advance-living', layout: 'hero', theme: 'ivory', icons: ['credit_card', 'coin'],
    headline: '현금서비스로\n**생활비**를 쓰고 있다면', sub: '빚이 빚을 부르기 전에 확인하세요',
    title: '현금서비스로 생활비를 쓴다면', promo: '현금서비스나 카드론으로 생활비를 메우고 있다면 개인회생을 검토해 보세요', biz: ['현금서비스로 생활비라면', '빚이 빚을 부르기 전에'], risk: 'low' },
  { id: 47, code: 'E07', slug: 'any-yes', layout: 'check', theme: 'white', checks: ['독촉 전화를 받고 있다', '급여 압류가 걱정된다', '빚이 줄지 않는다'],
    headline: '하나라도 **YES**라면', sub: '개인회생 상담을 받아 보세요',
    title: '하나라도 해당되면 상담하세요', promo: '독촉, 압류 걱정, 늘어나는 빚. 하나라도 해당된다면 개인회생 상담을 신청하세요', biz: ['하나라도 해당된다면', '개인회생 상담 받아 보세요'], risk: 'low' },
  { id: 48, code: 'E08', slug: 'rehab-or-bankruptcy', layout: 'hero', theme: 'mint', icons: ['balance_scale'],
    headline: '내 빚, **개인회생**일까\n**파산**일까?', sub: '소득이 있으면 회생, 갚기 어려우면 파산 검토',
    title: '개인회생? 파산? 나에게 맞는 절차', promo: '소득이 있으면 개인회생, 소득으로 갚기 어려우면 파산을 검토합니다. 상담 신청', biz: ['회생일까 파산일까', '나에게 맞는 절차 확인'], risk: 'low' },
  { id: 49, code: 'E09', slug: 'revolving-snowball', layout: 'hero', theme: 'navy', icons: ['credit_card', 'chart_increasing'],
    headline: '카드 **리볼빙**이\n눈덩이처럼 불었다면', sub: '리볼빙과 카드론도 개인회생 대상입니다',
    title: '리볼빙 잔액이 불어났다면', promo: '카드 리볼빙, 카드론 잔액이 계속 불어난다면 개인회생으로 정리를 검토하세요', biz: ['리볼빙이 눈덩이처럼', '카드론도 개인회생 대상'], risk: 'low' },
  { id: 50, code: 'E10', slug: 'within-three-years', layout: 'hero', theme: 'white', icons: ['hourglass_done'],
    headline: '지금 빚,\n**3년 안에** 갚을 수 있나요?', sub: '어렵다면 법이 정한 조정 방법이 있습니다',
    title: '3년 안에 갚기 어렵다면', promo: '지금 속도로 3년 안에 갚기 어렵다면 개인회생으로 변제계획을 세워 보세요', biz: ['3년 안에 갚기 어렵다면', '법이 정한 방법이 있어요'], risk: 'low' },
);

// ── F. 직업·상황 호명 ─────────────────────────────
add(
  { id: 51, code: 'F01', slug: 'office-worker', layout: 'hero', theme: 'blue', icons: ['briefcase'], eyebrow: '직장인 개인회생',
    headline: '**월급에 맞춰**\n갚는 방법이 있습니다', sub: '생계비를 뺀 소득으로 변제계획을 세웁니다',
    title: '직장인 개인회생, 월급 기준으로', promo: '직장인 개인회생은 월급에서 생계비를 뺀 금액으로 변제계획을 세웁니다', biz: ['직장인 개인회생', '월급에 맞춰 갚습니다'], risk: 'low' },
  { id: 52, code: 'F02', slug: 'business-owner', layout: 'hero', theme: 'sand', icons: ['convenience_store'],
    headline: '**사장님** 개인회생은\n계산법이 다릅니다', sub: '사업 소득과 경비를 반영해 계획을 세웁니다',
    title: '사장님 개인회생은 계산이 다릅니다', promo: '자영업자는 사업 소득과 경비를 반영해 변제계획을 세웁니다. 상담 신청', biz: ['사장님 개인회생', '계산법이 다릅니다'], risk: 'low' },
  { id: 53, code: 'F03', slug: 'gig-worker', layout: 'hero', theme: 'peach', icons: ['motor_scooter', 'laptop'],
    headline: '소득이 **들쭉날쭉**해도\n신청할 수 있습니다', sub: '배달·대리·프리랜서도 반복 소득이면 가능',
    title: '프리랜서, 배달기사 개인회생', promo: '배달, 대리, 프리랜서처럼 소득이 일정하지 않아도 개인회생을 신청할 수 있습니다', biz: ['소득이 들쭉날쭉해도', '개인회생 신청 가능'], risk: 'low' },
  { id: 54, code: 'F04', slug: 'public-servant', layout: 'hero', theme: 'navy', icons: ['office_building', 'military_helmet'],
    headline: '공무원·군인·교사도\n**개인회생** 할 수 있습니다', sub: '개인회생은 공무원 결격사유가 아닙니다', note: '국가공무원법 제33조',
    title: '공무원, 군인도 개인회생 가능합니다', promo: '개인회생은 국가공무원법상 결격사유가 아닙니다. 직업 걱정부터 상담하세요', biz: ['공무원 군인도 개인회생', '결격사유가 아닙니다'], risk: 'mid', src: 'law' },
  { id: 55, code: 'F05', slug: 'twenties', layout: 'hero', theme: 'white', icons: ['graduation_cap', 'backpack'],
    headline: '사회초년생의 빚,\n**20대에** 정리할 수 있습니다', sub: '시작이 생활비였어도 방법은 있습니다',
    title: '20대, 빚 정리 늦지 않았습니다', promo: '생활비로 시작된 20대의 빚, 개인회생으로 정리할 수 있는지 확인하세요', biz: ['20대의 빚, 지금 정리', '사회초년생 개인회생'], risk: 'low' },
  { id: 56, code: 'F06', slug: 'newlyweds', layout: 'hero', theme: 'mint', icons: ['couch_and_lamp'],
    headline: '결혼 전 빚이\n**신혼을 누른다면**', sub: '부양가족 수만큼 생계비를 인정받습니다',
    title: '부양가족 있으면 생계비도 늘어요', promo: '개인회생은 부양가족 수에 따라 생계비를 인정합니다. 가족 있는 분도 상담하세요', biz: ['결혼 전 빚이 무겁다면', '부양가족 생계비 인정'], risk: 'low' },
  { id: 57, code: 'F07', slug: 'breadwinner', layout: 'hero', theme: 'navy', icons: ['house'],
    headline: '가장의 빚,\n**가족 생계비**부터 지킵니다', sub: '4인 가구 생계비 389만 6,842원을 먼저 인정', note: '2026년 법원 기준 생계비',
    title: '가장의 빚, 생계비부터 지키세요', promo: '4인 가구 생계비 약 389만 원을 먼저 남기고 나머지 소득으로 갚습니다', biz: ['가장의 빚, 생계비부터', '4인 가구 389만 원 인정'], risk: 'low', src: 'living' },
  { id: 58, code: 'F08', slug: 'stock-crypto-loss', layout: 'hero', theme: 'charcoal', icons: ['chart_decreasing'],
    headline: '**주식·코인** 손실로\n생긴 빚이라면', sub: '투자로 생긴 빚도 개인회생을 신청할 수 있습니다',
    title: '주식, 코인 손실 빚도 개인회생', promo: '주식, 코인 투자 손실로 생긴 빚도 개인회생을 신청할 수 있습니다. 상담 신청', biz: ['주식 코인 손실 빚이라면', '개인회생 신청 가능'], risk: 'low' },
  { id: 59, code: 'F09', slug: 'guarantor-debt', layout: 'hero', theme: 'ivory', icons: ['handshake', 'page_with_curl'],
    headline: '남의 빚 **보증**으로\n떠안은 빚이라면', sub: '보증채무도 변제계획에 포함됩니다',
    title: '보증 선 빚도 개인회생 가능', promo: '남의 빚 보증으로 떠안은 채무도 개인회생 변제계획에 포함할 수 있습니다', biz: ['보증으로 떠안은 빚', '개인회생에 포함됩니다'], risk: 'low' },
  { id: 60, code: 'F10', slug: 'sixties', layout: 'hero', theme: 'sand', icons: ['older_person'],
    headline: '**60대**라도\n늦지 않았습니다', sub: '연금이나 근로소득이 있다면 신청할 수 있습니다',
    title: '60대 개인회생, 늦지 않았습니다', promo: '연금이나 근로소득이 있다면 나이와 관계없이 개인회생을 신청할 수 있습니다', biz: ['60대도 늦지 않았습니다', '연금 소득도 신청 가능'], risk: 'mid' },
);

// ── G. 제도 핵심 정보 ─────────────────────────────
add(
  { id: 61, code: 'G01', slug: 'one-line-summary', layout: 'hero', theme: 'ivory', icons: ['balance_scale'], eyebrow: '개인회생 한 줄 요약',
    headline: '소득으로 **3년** 갚고\n남은 빚은 **면책**', sub: '법원이 인가한 계획대로 갚는 제도', note: '비면책채권 제외, 결정은 법원이 합니다',
    title: '개인회생, 한 줄로 정리하면', promo: '개인회생은 소득으로 원칙 3년간 갚고 남은 빚을 면책받는 법원 제도입니다', biz: ['3년 갚고 남은 빚은 면책', '개인회생 한 줄 요약'], risk: 'mid' },
  { id: 62, code: 'G02', slug: 'process-steps', layout: 'steps', theme: 'ivory',
    steps: [['writing_hand', '상담'], ['clipboard', '서류 준비'], ['envelope_with_arrow', '신청'], ['balance_scale', '개시결정'], ['spiral_calendar', '인가·변제']],
    headline: '개인회생,\n**이렇게 진행됩니다**', note: '신청 때 금지명령을 함께 신청할 수 있습니다',
    title: '개인회생 진행 순서 한눈에', promo: '상담부터 신청, 개시결정, 인가까지 개인회생 진행 순서를 안내해 드립니다', biz: ['개인회생 진행 순서', '상담부터 인가까지'], risk: 'low' },
  { id: 63, code: 'G03', slug: 'keep-property', layout: 'hero', theme: 'teal', icons: ['house', 'shield'],
    headline: '**재산을 지키며**\n갚는 절차', sub: '개인회생은 재산을 처분하지 않습니다', note: '재산 가치 이상은 변제계획에 반영됩니다',
    title: '재산을 지키며 갚는 개인회생', promo: '개인회생은 파산과 달리 재산을 처분하지 않고 소득으로 갚는 절차입니다', biz: ['재산을 지키며 갚는 절차', '소득으로 갚는 개인회생'], risk: 'low' },
  { id: 64, code: 'G04', slug: 'plan-change', layout: 'hero', theme: 'mint', icons: ['memo'],
    headline: '갚다가 **소득이 줄면**\n계획을 바꿀 수 있습니다', sub: '인가 후에도 변경을 신청할 수 있습니다', note: '채무자회생법 제619조',
    title: '갚다가 소득이 줄면 어떻게 하죠?', promo: '개인회생 인가 후 소득이 줄면 변제계획 변경을 신청할 수 있습니다. 상담 신청', biz: ['소득이 줄면 계획 변경', '인가 후에도 신청 가능'], risk: 'low', src: 'law' },
  { id: 65, code: 'G05', slug: 'no-consent-needed', layout: 'hero', theme: 'navy', icons: ['balance_scale'],
    headline: '채권자가 반대해도\n**법원이 판단**합니다', sub: '채권자 동의는 필수 요건이 아닙니다', note: '법이 정한 요건에 따라 법원이 인가 여부를 결정합니다',
    title: '채권자 동의 없이도 진행됩니다', promo: '개인회생은 채권자 동의가 필수가 아니며 법이 정한 요건으로 법원이 판단합니다', biz: ['채권자가 반대해도', '법원이 판단합니다'], risk: 'low' },
  { id: 66, code: 'G06', slug: 'three-donts', layout: 'check', theme: 'white', mark: 'x', checks: ['신청 직전 추가 대출', '재산 명의 이전', '특정 채권자만 먼저 갚기'],
    headline: '신청 전 **이것만은**\n하지 마세요', note: '기각이나 불이익 사유가 될 수 있습니다',
    title: '개인회생 전 하지 말아야 할 3가지', promo: '신청 직전 대출, 재산 명의 이전, 특정 채권자만 갚기는 불리할 수 있습니다', biz: ['신청 전 하지 말 것 3가지', '개인회생 체크포인트'], risk: 'low' },
  { id: 67, code: 'G07', slug: 'principal-too', layout: 'hero', theme: 'sand', icons: ['page_facing_up'],
    headline: '이자만이 아니라\n**원금**도 조정됩니다', sub: '소득에 맞춰 갚고 남은 원금은 면책됩니다', note: '결정은 법원이 합니다',
    title: '개인회생은 원금도 조정됩니다', promo: '개인회생은 이자뿐 아니라 원금도 소득에 맞춰 조정하는 법원 절차입니다', biz: ['이자만이 아니라 원금도', '소득에 맞춰 조정'], risk: 'mid' },
  { id: 68, code: 'G08', slug: 'after-commencement', layout: 'check', theme: 'navy', checks: ['새로운 추심 금지', '진행 중인 압류 중지', '변제계획 심사 시작'],
    headline: '개시결정이 나면\n**달라지는 것**', note: '채무자회생법 제600조, 결정은 법원이 합니다',
    title: '개시결정 후 달라지는 3가지', promo: '개시결정이 나면 추심과 강제집행이 금지되고 진행 중인 압류가 중지됩니다', biz: ['개시결정 후 달라지는 것', '추심 금지, 압류 중지'], risk: 'mid', src: 'law' },
  { id: 69, code: 'G09', slug: 'lease-deposit', layout: 'hero', theme: 'ivory', icons: ['house', 'key'],
    headline: '**전세보증금**이 있어도\n신청할 수 있습니다', sub: '보증금 중 일정액은 재산에서 제외됩니다', note: '지역별 공제 기준이 적용됩니다',
    title: '전세보증금 있어도 개인회생 가능', promo: '임대차보증금이 있어도 개인회생을 신청할 수 있고 일정액은 재산에서 제외됩니다', biz: ['전세보증금 있어도 가능', '일정액은 재산에서 제외'], risk: 'low' },
  { id: 70, code: 'G10', slug: 'by-the-law', layout: 'type', theme: 'blue', icons: ['balance_scale'],
    headline: '빚 정리도\n**법대로** 하면 됩니다', sub: '채무자회생법에 따른 법원 절차, 개인회생',
    title: '빚 정리, 법대로 하면 됩니다', promo: '개인회생은 채무자회생법에 따라 법원이 진행하는 채무 조정 절차입니다', biz: ['빚 정리도 법대로', '법원 개인회생 절차'], risk: 'low' },
);

// ── H. 비밀·안심 ─────────────────────────────
add(
  { id: 71, code: 'H01', slug: 'confidentiality-duty', layout: 'hero', theme: 'teal', icons: ['locked', 'shield'],
    headline: '상담 내용은\n**비밀유지 의무** 대상입니다', sub: '변호사법 제26조가 정한 의무입니다',
    title: '빚 상담, 비밀은 법으로 지켜집니다', promo: '변호사는 직무상 알게 된 비밀을 누설할 수 없습니다. 안심하고 상담 신청하세요', biz: ['상담 비밀은 법으로', '변호사 비밀유지 의무'], risk: 'low', src: 'law' },
  { id: 72, code: 'H02', slug: 'court-mail-address', layout: 'hero', theme: 'ivory', icons: ['envelope_with_arrow', 'round_pushpin'],
    headline: '법원 우편물 받을 곳\n**따로 지정**할 수 있습니다', sub: '송달장소 신고 제도를 이용할 수 있습니다', note: '민사소송법 제184조',
    title: '법원 우편물, 받는 곳 지정 가능', promo: '개인회생 법원 우편물은 송달장소 신고로 받을 곳을 따로 지정할 수 있습니다', biz: ['법원 우편물 받는 곳 지정', '송달장소 신고 제도'], risk: 'mid', src: 'law' },
  { id: 73, code: 'H03', slug: 'worry-exposure', layout: 'hero', theme: 'sand', icons: ['worried_face'],
    headline: '가족·직장에\n**알려질까** 걱정이라면', sub: '진행 방식부터 비공개로 상담하세요',
    title: '가족, 직장이 알까 봐 걱정이라면', promo: '가족이나 직장에 알려질까 걱정된다면 진행 방식부터 변호사와 상담하세요', biz: ['가족이 알까 봐 걱정이라면', '비공개로 먼저 상담하세요'], risk: 'low' },
  { id: 74, code: 'H04', slug: 'name-and-phone', layout: 'hero', theme: 'white', icons: ['writing_hand', 'memo'],
    headline: '이름과 연락처만\n남기면 **신청 끝**', sub: '서류 준비는 상담 후에 시작합니다',
    title: '이름, 연락처만 남기면 신청 끝', promo: '이름과 연락처만 남기면 상담 신청이 끝납니다. 서류는 상담 후 준비합니다', biz: ['이름과 연락처만 남기면', '상담 신청 끝'], risk: 'mid' },
  { id: 75, code: 'H05', slug: 'paperwork-tired', layout: 'hero', theme: 'peach', icons: ['clipboard'],
    headline: '혼자 서류 준비하다\n**지치셨나요?**', sub: '복잡한 개인회생 서류, 함께 준비합니다',
    title: '개인회생 서류, 혼자 막막하다면', promo: '부채증명서부터 변제계획안까지, 개인회생 서류를 변호사와 함께 준비하세요', biz: ['혼자 서류 준비 지쳤다면', '개인회생 서류 함께 준비'], risk: 'low' },
  { id: 76, code: 'H06', slug: 'apply-at-night', layout: 'hero', theme: 'night', icons: ['crescent_moon', 'writing_hand'],
    headline: '잠 못 드는 밤에도\n**상담 신청**은 열려 있습니다', sub: '신청을 남기면 순서대로 연락드립니다',
    title: '밤에도 상담 신청할 수 있습니다', promo: '늦은 밤에도 상담 신청을 남길 수 있습니다. 신청 순서대로 연락드립니다', biz: ['밤에도 상담 신청 가능', '순서대로 연락드립니다'], risk: 'mid' },
  { id: 77, code: 'H07', slug: 'not-shameful', layout: 'hero', theme: 'mint', icons: ['folded_hands'],
    headline: '빚 이야기,\n**부끄러운 일 아닙니다**', sub: '올해 상반기에만 8만 건 넘게 신청했습니다', note: '법원행정처, 2026년 상반기 개인회생 신청 81,723건',
    title: '빚 고민, 부끄러운 일 아닙니다', promo: '올해 상반기에만 개인회생 신청이 8만 건을 넘었습니다. 혼자 고민하지 마세요', biz: ['빚 고민, 부끄럽지 않아요', '상반기 신청 8만 건 넘어'], risk: 'low', src: 'court2026h1' },
  { id: 78, code: 'H08', slug: 'decide-after', layout: 'hero', theme: 'teal', icons: ['hot_beverage'],
    headline: '결정은 **상담 후에**\n천천히 하셔도 됩니다', sub: '신청 전에 절차와 조건부터 확인하세요',
    title: '상담 후 천천히 결정하세요', promo: '개인회생 신청 여부는 상담으로 절차와 조건을 확인한 뒤 결정하셔도 됩니다', biz: ['결정은 상담 후에', '천천히 하셔도 됩니다'], risk: 'low' },
  { id: 79, code: 'H09', slug: 'not-alone-creditors', layout: 'hero', theme: 'charcoal', icons: ['shield'],
    headline: '채권자와 **혼자**\n싸우지 않아도 됩니다', sub: '개인회생은 법원 절차로 진행됩니다',
    title: '채권자와 혼자 싸우지 마세요', promo: '채권자와 한 곳씩 협상하지 않아도 됩니다. 개인회생은 법원 절차로 진행합니다', biz: ['채권자와 혼자 싸우지 마요', '법원 절차로 진행'], risk: 'low' },
  { id: 80, code: 'H10', slug: 'family-first', layout: 'hero', theme: 'white', icons: ['open_hands'],
    headline: '**가족이 먼저**\n알아봐도 괜찮습니다', sub: '가족의 빚 문제, 함께 상담할 수 있습니다',
    title: '가족 빚 문제, 대신 알아봐도 됩니다', promo: '부모, 자녀, 배우자의 빚 문제로 고민 중이라면 가족이 먼저 상담 신청해도 됩니다', biz: ['가족이 먼저 알아봐도 돼요', '가족의 빚 문제 상담'], risk: 'low' },
);

// ── I. 숫자로 보는 현실 (공식 통계, 출처 표기 필수) ─────────
add(
  { id: 81, code: 'I01', slug: 'stat-h1-record', layout: 'stat', theme: 'mint', stat: { label: '2026년 상반기 개인회생 신청', value: '81,723', unit: '건' },
    headline: '역대 상반기 가운데\n**가장 많았습니다**', note: '출처: 법원행정처(2026년 7월 발표)',
    title: '올해 상반기 개인회생 8만 건 넘어', promo: '2026년 상반기 개인회생 신청 8만 1,723건, 역대 최다입니다. 혼자 고민하지 마세요', biz: ['상반기 개인회생 8만 건', '지난해보다 13.2% 늘어'], risk: 'low', src: 'court2026h1' },
  { id: 82, code: 'I02', slug: 'stat-per-day', layout: 'stat', theme: 'white', stat: { label: '하루 평균 개인회생 신청', value: '약 450', unit: '건' },
    headline: '**당신만의 고민이**\n아닙니다', note: '2026년 상반기 81,723건 기준 계산 (법원행정처)',
    title: '하루 450건, 당신만이 아닙니다', promo: '올해 상반기 하루 평균 약 450건의 개인회생이 신청됐습니다. 상담 신청하세요', biz: ['하루 평균 약 450건', '당신만의 고민이 아닙니다'], risk: 'low', src: 'court2026h1' },
  { id: 83, code: 'I03', slug: 'stat-2025-total', layout: 'stat', theme: 'sand', stat: { label: '2025년 한 해 개인회생 신청', value: '14만 9천', unit: '여 건' },
    headline: '이제는 많은 사람이\n**선택하는 제도**입니다', note: '출처: 2026 사법연감',
    title: '작년 개인회생 신청 14만 9천여 건', promo: '2025년 한 해 개인회생 신청이 14만 9천여 건이었습니다. 방법부터 확인하세요', biz: ['작년 개인회생 14만 9천여 건', '많은 사람이 선택합니다'], risk: 'low', src: 'yearbook2025' },
  { id: 84, code: 'I04', slug: 'stat-10yr', layout: 'stat', theme: 'blue', stat: { label: '10년 새 상반기 개인회생 신청', value: '1.7', unit: '배' },
    headline: '빚 문제를 **법으로**\n푸는 사람이 늘었습니다', note: '2016년 4만 7,229건 → 2026년 8만 1,723건 (상반기, 법원행정처)',
    title: '개인회생, 10년 새 1.7배 늘었습니다', promo: '상반기 개인회생 신청은 10년 새 1.7배가 됐습니다. 법적 해결 방법을 확인하세요', biz: ['10년 새 1.7배 늘었어요', '개인회생 신청 건수'], risk: 'low', src: 'court2026h1' },
  { id: 85, code: 'I05', slug: 'stat-youth-debt', layout: 'stat', theme: 'peach', stat: { label: '29세 이하 신청자 평균 채무', value: '6,926', unit: '만 원' },
    headline: '10명 중 약 7명은\n**생활비**로 시작됐습니다', note: '출처: 서울시 조사(2025년 신청자 1,025명)',
    title: '20대 개인회생, 시작은 생활비', promo: '29세 이하 신청자 10명 중 약 7명은 생활비로 빚이 시작됐습니다(서울시 조사)', biz: ['시작은 생활비였습니다', '청년 개인회생'], risk: 'low', src: 'seoulYouth' },
  { id: 86, code: 'I06', slug: 'stat-yoy', layout: 'stat', theme: 'charcoal', stat: { label: '1년 새 늘어난 개인회생 신청', value: '13.2', unit: '%' },
    headline: '빚 부담을 느끼는\n**사람이 늘고 있습니다**', note: '2025년 상반기 72,192건 → 2026년 81,723건 (법원행정처)',
    title: '개인회생 신청 1년 새 13.2% 늘어', promo: '올해 상반기 개인회생 신청이 1년 전보다 13.2% 늘었습니다. 내 상황도 점검하세요', biz: ['1년 새 13.2% 늘어난 신청', '개인회생, 나도 해당될까'], risk: 'low', src: 'court2026h1' },
  { id: 87, code: 'I07', slug: 'high-debt-ok', layout: 'hero', theme: 'navy', icons: ['bank', 'money_bag'],
    headline: '빚이 **수억 원**이어도\n신청할 수 있습니다', sub: '무담보 10억 원, 담보 15억 원 이하', note: '채무자회생법 제579조',
    title: '고액 채무도 개인회생 가능합니다', promo: '무담보 10억 원, 담보 15억 원 이하라면 고액 채무도 개인회생을 신청할 수 있습니다', biz: ['빚이 수억 원이어도', '개인회생 신청 가능'], risk: 'low', src: 'law' },
  { id: 88, code: 'I08', slug: 'stat-2030', layout: 'stat', theme: 'teal', stat: { label: '서울회생법원 20·30대 개시결정 증가', value: '32.7', unit: '%' },
    headline: '젊은 층도 **법적 절차**로\n빚을 정리합니다', note: '2022년 6,913건 → 2023년 9,171건 (2025 개인회생 통계조사보고서)',
    title: '2030 개인회생 늘고 있습니다', promo: '서울회생법원의 20~30대 개시결정은 1년 새 32.7% 늘었습니다. 늦기 전에 확인하세요', biz: ['2030 개인회생 늘고 있어요', '젊은 층도 법으로 정리'], risk: 'low', src: 'seoulCourt2030' },
  { id: 89, code: 'I09', slug: 'law-change-2018', layout: 'type', theme: 'ivory', icons: ['scroll'],
    headline: '변제기간 최장 5년에서\n원칙 **3년**으로', sub: '2018년 법 개정으로 짧아졌습니다', note: '채무자회생법 제611조',
    title: '개인회생 변제기간, 3년으로 줄었습니다', promo: '2018년 법 개정으로 개인회생 변제기간은 원칙 3년이 됐습니다. 상담 신청하세요', biz: ['변제기간 원칙 3년', '2018년 법 개정'], risk: 'low', src: 'law' },
  { id: 90, code: 'I10', slug: 'stat-bankruptcy', layout: 'stat', theme: 'white', stat: { label: '2025년 개인파산 신청', value: '4만 909', unit: '건' },
    headline: '소득이 없다면\n**파산·면책**도 방법입니다', note: '출처: 2026 사법연감',
    title: '소득이 없다면 개인파산도 방법', promo: '갚을 소득이 없다면 개인파산과 면책을 검토할 수 있습니다. 상담 신청하세요', biz: ['소득이 없다면 개인파산', '파산 면책 절차 상담'], risk: 'low', src: 'yearbook2025' },
);
